build:
  version: "3.0"

#developerinfo:
loans:
  message: "Welcome to SandyzApp related Dev Z APIs "
  contactDetails:
    name: "Sandeep Dahiya - Producer"
    email: "DEVmail.sandeepdahiyalgmail.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934