build:
  version: "11.0"

#developerinfo:
loans:
  message: "Welcome to SandyzApp related prod Z APIs "
  contactDetails:
    name: "Sandeep Dahiya - Producer"
    email: "PRODmail.sandeepdahiyalgmail.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934