build:
  version: "2.0"

#developerinfo:
loans:
  message: "Welcome to SandyzApp related QA Z APIs "
  contactDetails:
    name: "Sandeep Dahiya - Producer"
    email: "QAmail.sandeepdahiyalgmail.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934